gb:
  name: guestbook-app
  labels:
    app: guestbook
    env: dev
    stack: guestbook
  image:
    repository: krutipatel15/guestbook-helm-frontend
    tag: v1
    pullPolicy: Always
  replicas: 3
  configmap:
    ## KEY: "value"
    BACKEND_URL: "http://gbapp-backend-service.db.svc.cluster.local"
  containerPorts:
      http: 5000
